branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - make docs

before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
